apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-env
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.env.supabaseUrl | quote }}
  SUPABASE_SERVICE_KEY: {{ .Values.env.supabaseServiceKey | quote }}
  SUPABASE_JWT_SECRET: {{ .Values.env.supabaseJwtSecret | quote }}
  FLASK_ENV: {{ .Values.env.flaskEnv | quote }}
  SECRET_KEY: {{ .Values.env.secretKey | quote }}
